# Data downloaders

In [2]:
# Automatically reload code in notebook
%load_ext autoreload
%autoreload 2

import os
os.chdir(os.path.dirname(os.path.abspath('.')))

import src.utils as utils
import src.onekg as og

## 1000 Genomes Project

The 1000 Genomes Project (1KG) has a lot of different versions of their genomic data, as well as additional data that came from offshoot projects. These are referred to as *collections* and a description of each can be found [here](https://www.internationalgenome.org/data-portal/data-collection).

The `onekg` submodule provides a way to easily find and download data from those projects, namely VCF files.


We can list all the different collections currently supported by the `onekg` submodule with the `get_ftp_dict` function. 

This also returns information about the manifest file (which contains metadata about the names and expected sizes of each file) as well as info about how to read each manifest file into `pandas` (used internally by other functions).

### VCFs

In [3]:
og.get_ftp_dict()

{'1000_Genomes_30x_on_GRCh38': {'description': 'VCFs from high-coverage WGS with SNVs, INDELs, and SVs. Details: https://www.internationalgenome.org/data-portal/data-collection/30x-grch38',
  'url': 'https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20220422_3202_phased_SNV_INDEL_SV/',
  'manifest': 'https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20220422_3202_phased_SNV_INDEL_SV/20220804_manifest.txt',
  'manifest_cols': ['fname', 'md5'],
  'manifest_sep': ' '},
 '1000_Genomes_on_GRCh38': {'description': 'VCFs from WGS with SNVs and INDELs. Details: https://www.internationalgenome.org/data-portal/data-collection/grch38',
  'url': 'http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/release/20190312_biallelic_SNV_and_INDEL/',
  'manifest': 'https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/20130502.phase3.analysis.sequence.index',
  'manifest_cols': ['fname', 'size', 'md5'],
  'manifest_sep': '\t'},
 'Human_Genome_Diversity_Project': {'description': 'VCFs from WGS with SNVs and INDELs. Details: https://www.internationalgenome.org/data-portal/data-collection/hgdp',
  'url': 'https://ngs.sanger.ac.uk/production/hgdp/hgdp_wgs.20190516/',
  'manifest': None,
  'manifest_cols': None,
  'manifest_sep': None}}

The `list_remote_vcf` function returns a manifest of the VCF files available for download for a given collection.

In [6]:
manifest  = og.list_remote_vcf(key="1000_Genomes_30x_on_GRCh38")
manifest.head()

,fname,md5,url,local
0,1kGP_high_coverage_Illumina.chr1.filtered.SNV_...,589762a43c412a34ff2dd76b009f06c6,https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/dat...,/grid/koo/home/schilder/projects/data/1KG/vcf/...
1,1kGP_high_coverage_Illumina.chr1.filtered.SNV_...,66b57b31dbce68f65ec2db64856bb266,https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/dat...,/grid/koo/home/schilder/projects/data/1KG/vcf/...
2,1kGP_high_coverage_Illumina.chr2.filtered.SNV_...,0f00e90423da451798a87c037a440669,https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/dat...,/grid/koo/home/schilder/projects/data/1KG/vcf/...
3,1kGP_high_coverage_Illumina.chr2.filtered.SNV_...,266321223ca7175d14472c2cd90e9640,https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/dat...,/grid/koo/home/schilder/projects/data/1KG/vcf/...
4,1kGP_high_coverage_Illumina.chr3.filtered.SNV_...,e13293cc80e060d731a0f3ce453168a1,https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/dat...,/grid/koo/home/schilder/projects/data/1KG/vcf/...

Now we can select a collection and download the VCF files with the `download_vcfs` function. In this case, we are selecting the `"1000_Genomes_30x_on_GRCh38"` collection, which contains VCFs of high-coverage WGS data from 3202 individuals.

**NOTE**: These files are quite large and can take a long time to download.

In [ ]:
vcf_files = og.download_vcfs(key="1000_Genomes_30x_on_GRCh38")

We can also donwload VCFs from another collection, such as the `"Human_Genome_Diversity_Project"` collection, which contains VCFs of WGS data from 929 diverse individuals.

These VCFs files were not directly provided by 1KG, but instead post-processed by the Sanger Insitute and distributed on a separate server. This is all handled automatically by `download_vcfs`.

**NOTE**: These files are quite large and can take a long time to download.

In [ ]:
vcf_files = og.download_vcfs(key="Human_Genome_Diversity_Project")

### Metadata

`onekg` has additional functions for getting relevant metadata like sample IDs and population (ancestry) IDs.

**Population metadata**: 
Contains information about each population, and which superpopulation they're part of.

In [9]:
pop = og.get_pop()
pop.head()

,Population Description,Population Code,Super Population,DNA from Blood,Offspring available from trios,Pilot Samples,Phase1 Samples,Final Phase Samples,Total
CDX,"Chinese Dai in Xishuangbanna, China",CDX,EAS,no,yes,0.0,0.0,99.0,99.0
CHB,"Han Chinese in Bejing, China",CHB,EAS,no,no,91.0,97.0,103.0,106.0
JPT,"Japanese in Tokyo, Japan",JPT,EAS,no,no,94.0,89.0,104.0,105.0
KHV,"Kinh in Ho Chi Minh City, Vietnam",KHV,EAS,yes,yes,0.0,0.0,101.0,101.0
CHS,"Southern Han Chinese, China",CHS,EAS,no,yes,0.0,100.0,108.0,112.0

**Pedigree metadata**: 
contains information about how some individuals within the cohort are related to each other.

In [10]:
ped = og.get_ped()
ped.head()

,Family ID,Individual ID,Paternal ID,Maternal ID,Gender,Phenotype,Population,Relationship,Siblings,Second Order,Third Order,Children,Other Comments,phase 3 genotypes,related genotypes,omni genotypes,affy_genotypes
HG00096,HG00096,HG00096,0,0,1,0,GBR,unrel,0,0,0,0,0,1,0,1,1
HG00097,HG00097,HG00097,0,0,2,0,GBR,unrel,0,0,0,0,0,1,0,1,1
HG00098,HG00098,HG00098,0,0,1,0,GBR,unrel,0,0,0,0,0,0,0,1,1
HG00099,HG00099,HG00099,0,0,2,0,GBR,unrel,0,0,0,0,0,1,0,1,1
HG00100,HG00100,HG00100,0,0,2,0,GBR,unrel,0,0,0,0,0,1,0,1,1

`get_sample_metadata` is a function that merges together the pedigree and population metadata to give a mapping for each individual to their population and superpopulation.

In [11]:
sample_metadata = og.get_sample_metadata()
sample_metadata.head()

,Family ID,Individual ID,Paternal ID,Maternal ID,Gender,Phenotype,Population,Relationship,Siblings,Second Order,...,affy_genotypes,Population Description,Population Code,Super Population,DNA from Blood,Offspring available from trios,Pilot Samples,Phase1 Samples,Final Phase Samples,Total
HG00096,HG00096,HG00096,0,0,1,0,GBR,unrel,0,0,...,1,British in England and Scotland,GBR,EUR,no,yes,0.0,89.0,92.0,94.0
HG00097,HG00097,HG00097,0,0,2,0,GBR,unrel,0,0,...,1,British in England and Scotland,GBR,EUR,no,yes,0.0,89.0,92.0,94.0
HG00098,HG00098,HG00098,0,0,1,0,GBR,unrel,0,0,...,1,British in England and Scotland,GBR,EUR,no,yes,0.0,89.0,92.0,94.0
HG00099,HG00099,HG00099,0,0,2,0,GBR,unrel,0,0,...,1,British in England and Scotland,GBR,EUR,no,yes,0.0,89.0,92.0,94.0
HG00100,HG00100,HG00100,0,0,2,0,GBR,unrel,0,0,...,1,British in England and Scotland,GBR,EUR,no,yes,0.0,89.0,92.0,94.0